### ISSUE TITLE
Feature request -  Suporte para configurações de autenticação do QGIS

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/recart-plugin#10]
Actualmente o plugin não suporta que as credenciais da ligação PostGIS sejam guardadas em configurações de autenticação encriptadas, que é a forma preferência para guardar credenciais sem o perigo que as mesmas venham a ser expostas a terceiro por partilha de projectos ou definition files.

Isto obriga o utilizador do plugin a introduzir as suas credenciais diversas vezes durante o processo de validação e exportação.

**Comment by jgrocha** [comment]
@SrNetoChan Quando puderes, testa este feature, sff.  Se não resolver os teus casos de uso, volta a abrir o issue.

**Comment by SrNetoChan** [comment]
@jgrocha assim o farei.

Para não estar à espera do zip, que comando é preciso correr para actualizar os ficheiros do plugin?

**Comment by jgrocha** [comment]
@SrNetoChan O [zip](https://github.com/dgterritorio/recart-plugin/blob/main/plugin/recartDGT.zip) que está publicado tem estas alterações.

**Comment by SrNetoChan** [comment]
@jgrocha confirmo que funciona bem. Obrigado!
