### ISSUE TITLE
Erro na exportação para formato shp dos segmentos da rede viária

### ISSUE THREAD

**Issue by gvarela96** [dgterritorio/recart-plugin#12]
Boa tarde,

Quando tento exportar para formato _shapefile_  os segmentos das vias rodoviárias obtenho o seguinte erro (imagem em anexo).

O problema advém da bd construída em postgreSQL ou será do próprio plugin?

Obrigado pela vossa atenção.
Boas festas!

Gonçalo
![Captura de ecrã 2021-12-21 101355](https://user-images.githubusercontent.com/96472796/146912730-9956a431-5185-4fda-8b02-edceaa7eb447.png)

**Comment by jgrocha** [comment]
Inconsistência bem identificada @gvarela96 

Na verdade, na [especificação](https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/NormasEspecificacoesTecnicasCartTop.pdf) (pág 63, CartTop-V1.1) não aparece o atributo **larguraViaRodov**. Contudo este aparece no Dicionário de Objetos relativo ao [SegViaRodov](https://www.dgterritorio.gov.pt/recart/TRANSPORTES%20(Transporte%20rodovi%C3%A1rio)/SegViaRodov.html#page_larguraViaRodov). Aparentemente há uma pequena inconsistência entre a especificação e o dicionário de objetos.

O plugin está a usar o (json do) dicionário de objetos para criar a exportação. Na criação de uma nova base de dados também estamos a acrescentar esse atributo. O [DDL](https://github.com/dgterritorio/RECART/blob/master/recart.ddl) disponível no repositório recart também tem esse atributo. Portanto, a minha sugestão é acrescentar este atributo `largura_via_rodov` ao seu modelo CartTop.

```sql
alter table seg_via_rodov add column largura_via_rodov real;
```

Vou manter o issue em aberto, para se poder discutir a melhor solução. Penso que a solução passa por acrescentar esta inconsistência à [errata](https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/NormasEspecificacoesTecnicasCartTopErrata.pdf) já existente.

Talvez o @dgterritorio possa acrescentar algo a esta questão.

**Comment by aserronha** [comment]
Bom dia,

É uma gralha no documento das especificações técnicas... que está identificada mas não está refletida na errata. Não está refletido ainda na errata porque era suposto sair em breve uma nova versão das especificações. A DGT vai decidir se acrescenta à errata ou se vem refletido apenas na próxima versão das especificações técnicas.

Se estiver a usar a [BD versão 1.2](https://github.com/dgterritorio/RECART/releases/tag/v1.1.2) esse atributo já existe!

Pode experimentar a descarregar essa versão ou então seguir a sugestão do @jgrocha 

![imagem](https://user-images.githubusercontent.com/46351849/146922046-ab774fb9-6be9-45cd-a900-0ffd4ce6db01.png)

**Comment by aserronha** [comment]
Acrescentamos ainda que pode tirar partido da extração dos "Segmentos da via rodoviária" para o formato _shapefile_ se seleccionar também a tabela via_rodov com os nomes das vias (é uma mais valia se estiver bem feita a ligação entre os segmentos e os nomes das vias).
