### ISSUE TITLE
WARNING    Feature type or srid for geometria of "public"."barreira" could not be determined

### ISSUE THREAD

**Issue by SrNetoChan** [dgterritorio/recart-plugin#17]
Não me parece relevante, mas o QGIS está a dar-me o seguinte warning quando carrego uma base de dados para projecto.

```
2021-12-30T09:45:37     WARNING    Feature type or srid for geometria of "public"."barreira" could not be determined or was not requested.
```

Tanto quanto me apercebo as duas camadas de barreira funcionam como esperado.

**Comment by jgrocha** [comment]
Isso geralmente acontece quando a tabela está vazia. Se estiver vazia, no scan da tabela o QGIS não consegue descobrir nem o tipo de geometria, nem o SRID. Será o caso?

**Comment by SrNetoChan** [comment]
Neste caso a tabela public.barreira tem 0 elementos do tipo linestring e 74 elementos do tipo polygon.
É possível que seja a camada das linestrings que se está a queixar.

Suponho que isso só acontece quando as tabelas são do tipo geometry(). Estranhamente tenho uma tabela de edifícios vazia e ele não se queixa.

Como disse, não me parece relevante, podem fechar se o entenderem. Reportei apenas para vosso conhecimento.

**Comment by jgrocha** [comment]
Algumas das tabelas do Recart têm o tipo de geometria genérico `geometry`. Outras têm um tipo de geometria mais concreto, como `point`ou `polygon`. 

Para os casos em que o tipo de geometria é genérico, vamos ter estes avisos do QGIS. Podem ser ignorados e advêm do facto de as tabelas terem um tipo de geometria genérico.

Vou fechar este assunto, mas fica aqui a justificação para o aviso do QGIS.
