### ISSUE TITLE
Erro na importação de Ecopontos

### ISSUE THREAD

**Issue by RainIsGood** [dgterritorio/recart-plugin#19]
Bom dia,

No módulo de importação, ficheiros que contenham o código:  6150402 - Ecoponto
geram o seguinte erro, aborta e ja' não conclui o processo de importação.

Enviamos 2 exemplos em anexo para reprodução do erro, codificados com ULink :

(1)
Com-Ecopontos-v7.dgn  -  tem 12 elementos pontuais dos quais 4 são Ecopontos - importação falha
```
Processar Dataset
Foram processadas 12 features
Converter dados
[Erro -3]
	Exception: Error while connecting to PostgreSQL column "valor_tipo_de_mob_urbano_sinal" of relation "mob_urbano_sinal" does not exist
LINE 1: ...o eco1.mob_urbano_sinal(geometria, inicio_objeto, valor_tipo...
```
(2)
Sem-Ecopontos-v7.dgn  -  tem 8 elementos pontuais, retirados os Ecopontos - importação ok
```
Processar Dataset
Foram processadas 8 features
Converter dados
	Foram convertidas 3 features para a camada ponto_cotado
	Foram convertidas 5 features para a camada ponto_interesse

	Total convertido: 8 features (100.00%)
```
Agradecíamos verificação.
Obrigado.
 
[Ecopontos.zip](https://github.com/dgterritorio/recart-plugin/files/7793616/Ecopontos.zip)

**Comment by jgrocha** [comment]
Confirmo. O campo é designado por `valorTipoMobUrbSinal` do dicionário de dados e transformado automaticamente em `valor_tipo_mob_urb_sinal`, diferente de `valor_tipo_de_mob_urbano_sinal`.

Corrigindo o nome no dicionário de dados, este item fica resolvido. Vou testar e submeter a solução.

**Comment by jgrocha** [comment]
@RainIsGood O issue foi fechado automaticamente pelo PR #24 associado. Se vir que há ainda algum problema na importação, por favor volte a abrir o issue.
