### ISSUE TITLE
Módulo Importação - Correção de alguns Mapeamentos que estão incorretos

### ISSUE THREAD

**Issue by RainIsGood** [dgterritorio/recart-plugin#20]
Bom dia,

no ficheiro 'mapping.py' estão alguns mapeamentos incorretos que necessitam ser corrigidos:
```
4090102 – Toponímia - Campos de Jogos
```
está a criar uma entrada na tabela "constru_polig"
deveria ser desativado tal como a gama de códigos de Toponímia que o antecedem e sucedem.

```
7050100 - Área Para Tratamento de Resíduos Sólidos
7050300 - Área Para Tratamento de Resíduos Industriais
7050600 - Área de Aterro Sanitário
```
estão a referenciar a tabela 'equip_util_coletiva' mas deveria ser a tabela 'inst_gestao_ambiental' o que faz com que as 'Área Para Tratamento de Resíduos Sólidos' etc. sejam classificadas como um 'Equipamento de Utilização Coletiva' de 'Educação e investigação' ou 'Ação social'
```
12010605 - Linha Água Encoberta
```
tem as aspas em falta nos valores 4 e 0 (que todos os outros códigos usam) o que poderá causar algum problema à posteriori.

Obrigado.

**Comment by jgrocha** [comment]
O @aserronha já fez estas correções. Vou publicar um novo zip e podemos fechar este issue.

**Comment by RainIsGood** [comment]
Ok, obrigado.
