### ISSUE TITLE
para apagar

### ISSUE THREAD

**Issue by RainIsGood** [dgterritorio/recart-plugin#22]
para apagar

**Comment by aserronha** [comment]
Viva,

A questão tem a ver com o facto de não ser possível estabelecer esse processo de forma automática.

Nos edifícios é possível esse automatismo já que dizemos que também vai para determinado valor na tabela sem geometria.

No caso das vias rodoviárias para que é que querem **uma relação que não é possível estabelecer** entre a geometria (Segmento da via rodoviária) e a toponímia (Via rodoviária) já para não falar nos limites. 

Será que sabe que do lado do CAD (DGN/DWG) essa relação não existe e são códigos que vivem separados sem relação estabelecida e que mesmo com automatismos de análise espacial os segmentos poderiam ligar a topónimos diferentes?

O objetivo passa por o utilizador final estabelecer essas relações a partir das tabelas auxiliares para onde a toponímia vai. 

Não há nada a fazer porque é assim que se encontram os dados fonte.

**Comment by aserronha** [comment]
Boa tarde,

Por uma questão de transparência preferíamos que as issues se fechassem em vez de se apagarem.

A dúvida é pertinente e teve uma resposta. Se apagarem, alguém que tenha a mesma dúvida não poderá recorrer a uma resposta que já foi dada.

Cumprimentos.
