### ISSUE TITLE
bug de visualização da informação

### ISSUE THREAD

**Issue by asalvaterra** [dgterritorio/recart-plugin#39]
Boa tarde,

Antes de mais parabenizar quem construiu este plugin que é de grande utilidade para as entidades produtoras. 
Desta forma, acho que também é nosso dever alertar para eventuais bug’s que possam ser corrigidos para bem da comunidade utilizadora.

Após a utilização da funcionalidade CartTop para QGIS, GPKG, JSON e SHP do plugin recartDGT
![image](https://user-images.githubusercontent.com/62557275/158636168-25e96515-268a-4139-8126-924b6b5ff36b.png)

 
Carregamos num projeto QGIS os Temas Toponímia, Altimetria, Hidrografia e Transportes da totalidade do município de Santana do Arquipélago da Madeira
 
![image](https://user-images.githubusercontent.com/62557275/158636224-ab17f1ed-7096-4dbb-b3d5-a003aecd381c.png)

Acontece que depois de exportar, se fizermos Zoom to Group, não conseguimos visualizar nenhum layer.
 
![image](https://user-images.githubusercontent.com/62557275/158636298-c8b50074-837b-4cfe-bea8-1727a45a2819.png)
![image](https://user-images.githubusercontent.com/62557275/158636377-9ab11913-cfbe-43f5-a4cf-ab45f1f54b61.png)

 
Verificamos que quando fazemos Zoom to Group a escala associada a este display é de 1:89094

Mas se a escala escolhida for até 1:24999 conseguimos ver todos os temas exportados, mas não na sua totalidade, como se pode ver na imagem abaixo.

 
![image](https://user-images.githubusercontent.com/62557275/158636456-d99e9cd4-83b0-4854-9243-de2cbc6368d8.png)

Achamos que é uma limitação de display, mas que só ocorre se carregarmos as BD’s através da funcionalidade CartTop para QGIS, GPKG, JSON e SHP.

Como se pode verificar pela imagem abaixo, temos todos os temas carregados para a totalidade da Ilha da Madeira e conseguimos visualizar.
 
![image](https://user-images.githubusercontent.com/62557275/158636515-55f2ffa1-0214-430e-bfee-1d8485b57db3.png)

Achamos por bem transmitir esta ocorrência de forma a ser corrigida.

**Comment by aserronha** [comment]
Boa tarde,

Não é nenhum bug, nem nenhuma limitação de display. A funcionalidade CartTop para QGIS tem o objetivo de disponibilizar uma cartografia com simbologia adequada e com alguma legibilidade até à escala 1:25000.

Quem não quiser ver a simbologia desta forma pode executar o plugin e depois pode simplesmente editar cada camada para visualizar a cartografia como quiser (sem limites ou intervalos de escala definidos a gosto) ou então o utilizador pode simplesmente conectar-se à respetiva base de dados e a cada camada, sem o auxílio do plugin.

**Comment by asalvaterra** [comment]
Bom dia,

muito obrigada pelo rápido esclarecimento.

**Comment by aserronha** [comment]
Para concluir queríamos apenas referir que existem temas que não têm limites de escala na visualização, como por exemplo, as unidades administrativas e o tema auxiliar (área de trabalho).
