### ISSUE TITLE
Erro instalação pulgin v1.4 - QGIS version: 3.16.11-Hannover Hannover

### ISSUE THREAD

**Issue by LuisSimoesRoxo** [dgterritorio/recart-plugin#42]
Couldn't load plugin 'recart-plugin-1.4/plugin' 

ModuleNotFoundError: No module named 'recart-plugin-1' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS31~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'recart-plugin-1'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.11-Hannover Hannover, 26cc1c76

**Comment by SrNetoChan** [comment]
Como foi instalado o plugin? Pelo erro, a pasta de instalação não me parece correcta.

**Comment by LuisSimoesRoxo** [comment]
Olá Alexandre,

A instalação foi feita pelo gestor de plugins, install from ZIP.

obrigado

**Comment by SrNetoChan** [comment]
Tem de usar o ficheiro recartDGT.zip disponível na release v1.4
