### ISSUE TITLE
Casas decimais no script descontinuidades e regra 4_9_1 

### ISSUE THREAD

**Issue by sandraedia** [dgterritorio/recart-plugin#44]
Boa tarde,
Ao executar o script para as descontinuidades e a regra 4_9_1 (Plugin recart_DGT) dos objetos 3D resultou um elevado número de erros com grande quantidade de casas decimais (15). Para corrigir estes “falsos” erros foi alterado na base de dados o número de casas decimais para 3 eliminando assim estes erros. Este foi um procedimento de teste, é uma solução? Podemos aplicar de forma definitiva à base de dados?

![Desc](https://user-images.githubusercontent.com/61501678/212647588-2626d5f5-1bf8-4076-95a2-08410a4a0b02.png)

Obrigada

**Comment by dgterritorio** [comment]
Bom dia.
Sim. é a melhor solução para eliminar os erros de conetividade causados por coordenadas com muitas casas decimais. O arredendamento à terceira casa decimal é mais que suficiente para garantir a precisão exigida.
