### ISSUE TITLE
O módulo 'Verificar Regras CarTop' atual (Recart v1.2.4 - 2021/11/22) esta' a parar com dois erros

### ISSUE THREAD

**Issue by RainIsGood** [dgterritorio/recart-plugin#5]
Bom dia,

O módulo 'Verificar Regras CarTop' atual (Recart v1.2.4 - 2021/11/22) esta' a parar com dois erros, independentemente dos dados de entrada, que impossibilitam correr a verificação das regras, seja uma apenas, ou todas.

As versões que estamos a usar são as últimas de:
Windows 10
QGis 3.22
GDAL/OGR 3.3.3
PostgreSQL 14

Log gerado para validar apenas a 'Equidistância natural':

```
Conexões Postgis atualizadas
Validar base de dados...
	A criar estrutura de validação ...
[Erro]
	Exception: Error while connecting to PostgreSQL column a.id_curso_de_agua_area does not exist
LINE 712:     coalesce(a.id_curso_de_agua_area, 'aaaaaaaa-aaaa-aaaa-aa...
                       ^

	A executar validações ...

	A executar validação 're3_2 Equidistância natural' (1 de 1)
[Erro]
	Exception: Error while connecting to PostgreSQL procedure validation.do_validation(boolean, unknown) does not exist
LINE 1: call validation.do_validation(false, 're3_2');
             ^
HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.

Terminada a validação
```

Dizemos independentemente dos dados de entrada porque falha também com os dados de exemplo da DGT 'Extrato_SCN10k' disponível no site. 

https://www.dgterritorio.gov.pt/cartografia/cartografia-topografica/scn10k
https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/Extrato_SCN10k.zip
 
Para reproduzirem o problema importar o ficheiro 'extracto_332_1_mnt.dgn' usando ULinks, o que dá:

	Foram convertidas 8 features para a camada agua_lentica
	Foram convertidas 2852 features para a camada area_agricola_florestal_mato
	Foram convertidas 2 features para a camada areas_artificializadas
	Foram convertidas 755 features para a camada cabo_electrico
	Foram convertidas 180 features para a camada constru_linear
	Foram convertidas 56 features para a camada constru_polig
	Foram convertidas 517 features para a camada curso_de_agua_area
	Foram convertidas 385 features para a camada curso_de_agua_eixo
	Foram convertidas 441 features para a camada curva_de_nivel
	Foram convertidas 707 features para a camada edificio
	Foram convertidas 28 features para a camada elem_assoc_agua
	Foram convertidas 847 features para a camada elem_assoc_eletricidade
	Foram convertidas 6 features para a camada freguesia
	Foram convertidas 29 features para a camada linha_de_quebra
	Foram convertidas 46 features para a camada margem
	Foram convertidas 408 features para a camada obra_arte
	Foram convertidas 310 features para a camada ponto_cotado
	Foram convertidas 99 features para a camada seg_via_ferrea
	Foram convertidas 796 features para a camada seg_via_rodov
	Foram convertidas 1465 features para a camada via_rodov_limite
	Foram convertidas 26 features para a camada zona_humida

	Total convertido: 9963 features (96.48%)
	361 features ficaram por converter (3.50%)
	3 features resultaram em erro (0.03%)

Mas em seguida o módulo 'Verificar Regras CarTop' produz exatamente os erros acima apresentados.

Agradecíamos assim que possível uma solução para ultrapassar este problema.

**Comment by jgrocha** [comment]
Caro @RainIsGood 

Fiz um PR #6 que julgo que corrige os problemas identificados. Depois de instalada esta nova versão, fui capaz de usar o [dataset do exemplo](https://www.dgterritorio.gov.pt/sites/default/files/ficheiros-cartografia/Extrato_SCN10k.zip) referido para testar as três componentes do plugin.

### Conversão do Extrato_SCN10k para CartTop

Guardado num esquema `mnc`

![Screenshot from 2021-11-22 16-42-04](https://user-images.githubusercontent.com/163681/142903838-37bc5dec-33cf-4875-b7a6-27cf90bf69aa.png)

### Conversão p/ projecto QGIS

Visualização dos dados no esquema `mnc`

![Screenshot from 2021-11-22 16-43-29](https://user-images.githubusercontent.com/163681/142903852-a7616384-4d14-481c-b3d9-9960f43aa267.png)

### Validação do CartTop gerado a partir da conversão

Validação dos dados no esquema `mnc`

![Screenshot from 2021-11-22 17-04-23](https://user-images.githubusercontent.com/163681/142904014-fc1ab2cf-c253-4361-aa8a-8c436b360b42.png)

Assim que o PR #6 for integrado, automaticamente este issue será fechado.

**Comment by RainIsGood** [comment]
Caro Jorge,
ficou resolvido o problema, quer no dataset de exemplo, quer nos dados em que estamos a trabalhar. Faz agora a validação de todas as regras corretamente.
Nesta nova versão 1.2.5 ficou também resolvida a aplicação automática da nova simbologia.

Muito obrigado pela pronta resolução.

Fica também a sugestão de na descrição do plugin ser indica a funcionalidade das duas checkboxes "Mapear com nome de camada" e "Mapeamento personalizado", pois podem porventura ser úteis com certos tipos de dados. Obrigado.
